version: '3'

services:
  web:
    stdin_open: true
    container_name: nodeweb
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app 